//! Writes the table of an asset bundle for `addAssets` in build.zig:
//! `gen <output.zig> <prefix> <dir>`, for every file under `dir`.

const std = @import("std");

/// The encodings `EmbeddedOptions` takes a copy in, by their field names.
const Precompressed = enum { br, zstd, gzip };

const Asset = struct {
    name: []const u8,
    version: [8]u8,
    /// Indexed by `Precompressed`.
    compressed: [std.enums.values(Precompressed).len]?[]const u8 = @splat(null),
};

pub fn main(init: std.process.Init) !void {
    const arena = init.arena.allocator();
    const io = init.io;
    const args = try init.minimal.args.toSlice(arena);
    if (args.len != 4) {
        std.debug.print("usage: {s} <output.zig> <prefix> <dir>\n", .{args[0]});
        std.process.exit(1);
    }
    const output = args[1];
    const prefix = std.mem.trimEnd(u8, args[2], "/");
    var dir = try std.Io.Dir.cwd().openDir(io, args[3], .{ .iterate = true });
    defer dir.close(io);

    var names: std.StringArrayHashMapUnmanaged(void) = .empty;
    var walker = try dir.walk(arena);
    defer walker.deinit();
    while (try walker.next(io)) |entry| {
        if (entry.kind != .file) continue;
        const name = try arena.dupe(u8, entry.path);
        std.mem.replaceScalar(u8, name, std.fs.path.sep, '/');
        try names.put(arena, name, {});
    }
    names.sort(struct {
        keys: []const []const u8,
        pub fn lessThan(ctx: @This(), a: usize, b: usize) bool {
            return std.mem.lessThan(u8, ctx.keys[a], ctx.keys[b]);
        }
    }{ .keys = names.keys() });

    var assets: std.ArrayList(Asset) = .empty;
    for (names.keys()) |name| {
        // A compressed copy goes with its plain file, when there is one.
        if (compressedCopy(name)) |copy| {
            if (names.contains(copy.of)) continue;
        }
        const data = try dir.readFileAlloc(io, name, arena, .unlimited);
        var asset: Asset = .{ .name = name, .version = version(data) };
        for (std.enums.values(Precompressed)) |encoding| {
            const copy = try std.mem.concat(arena, u8, &.{ name, extension(encoding) });
            if (names.contains(copy)) asset.compressed[@intFromEnum(encoding)] = copy;
        }
        try assets.append(arena, asset);
    }

    var out: std.Io.Writer.Allocating = .init(arena);
    const w = &out.writer;
    try w.writeAll("// Generated by dusty's addAssets - do not edit\n");
    try w.writeAll("const File = @import(\"root.zig\").File;\n\n");
    try w.print("pub const prefix = \"{f}\";\n\n", .{std.zig.fmtString(prefix)});
    try w.writeAll("pub const files = [_]File{\n");
    for (assets.items) |asset| {
        const path = try std.fmt.allocPrint(arena, "{s}/{f}", .{ prefix, fmtPath(asset.name) });
        try w.print("    .{{ .name = \"{f}\", .path = \"{f}\", .version = \"{s}\", .url = \"{f}?v={s}\", .data = @embedFile(\"files/{f}\")", .{
            std.zig.fmtString(asset.name),
            std.zig.fmtString(path),
            asset.version,
            std.zig.fmtString(path),
            asset.version,
            std.zig.fmtString(asset.name),
        });
        for (std.enums.values(Precompressed), asset.compressed) |encoding, copy| {
            const c = copy orelse continue;
            try w.print(", .{s} = @embedFile(\"files/{f}\")", .{ @tagName(encoding), std.zig.fmtString(c) });
        }
        try w.writeAll(" },\n");
    }
    try w.writeAll("};\n");

    try std.Io.Dir.cwd().writeFile(io, .{ .sub_path = output, .data = out.written() });
}

fn extension(encoding: Precompressed) []const u8 {
    return switch (encoding) {
        .br => ".br",
        .zstd => ".zst",
        .gzip => ".gz",
    };
}

fn compressedCopy(name: []const u8) ?struct { of: []const u8 } {
    for (std.enums.values(Precompressed)) |encoding| {
        if (std.mem.endsWith(u8, name, extension(encoding))) {
            return .{ .of = name[0 .. name.len - extension(encoding).len] };
        }
    }
    return null;
}

/// Changes whenever the content does, for links to it to change too.
fn version(data: []const u8) [8]u8 {
    const hash: u32 = @truncate(std.hash.Wyhash.hash(0, data));
    var out: [8]u8 = undefined;
    _ = std.fmt.bufPrint(&out, "{x:0>8}", .{hash}) catch unreachable;
    return out;
}

/// Percent-encodes everything but unreserved characters and the slashes,
/// so the path is the same in a link and in the request for it, and a
/// segment can't start with the `:` or `*` of a route pattern.
fn fmtPath(name: []const u8) std.fmt.Alt([]const u8, formatPath) {
    return .{ .data = name };
}

fn formatPath(name: []const u8, w: *std.Io.Writer) std.Io.Writer.Error!void {
    for (name) |c| switch (c) {
        'A'...'Z', 'a'...'z', '0'...'9', '-', '.', '_', '~', '/' => try w.writeByte(c),
        else => try w.print("%{X:0>2}", .{c}),
    };
}

test fmtPath {
    var buf: [64]u8 = undefined;
    try std.testing.expectEqualStrings("img/my%20logo.svg", try std.fmt.bufPrint(&buf, "{f}", .{fmtPath("img/my logo.svg")}));
    try std.testing.expectEqualStrings("%3Aid%23x/%C3%BC.txt", try std.fmt.bufPrint(&buf, "{f}", .{fmtPath(":id#x/\u{fc}.txt")}));
}
